# Ferrum shell configuration

# Homebrew on Apple Silicon
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

eval "$(starship init zsh)"

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

# Autosuggestion color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#4c566a"

# Cohesive syntax highlighting
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]="fg=#d8dee9"
ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=#bf616a"
ZSH_HIGHLIGHT_STYLES[reserved-word]="fg=#b48ead,bold"
ZSH_HIGHLIGHT_STYLES[suffix-alias]="fg=#88c0d0"
ZSH_HIGHLIGHT_STYLES[global-alias]="fg=#88c0d0"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=#81a1c1"
ZSH_HIGHLIGHT_STYLES[commandseparator]="fg=#4c566a"
ZSH_HIGHLIGHT_STYLES[autodirectory]="fg=#88c0d0,underline"
ZSH_HIGHLIGHT_STYLES[path]="fg=#88c0d0,underline"
ZSH_HIGHLIGHT_STYLES[path_pathseparator]="fg=#81a1c1"
ZSH_HIGHLIGHT_STYLES[path_prefix]="fg=#88c0d0"
ZSH_HIGHLIGHT_STYLES[command]="fg=#81a1c1,bold"
ZSH_HIGHLIGHT_STYLES[alias]="fg=#88c0d0"
ZSH_HIGHLIGHT_STYLES[builtin]="fg=#81a1c1"
ZSH_HIGHLIGHT_STYLES[function]="fg=#88c0d0"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=#b48ead"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=#b48ead"
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]="fg=#b48ead"
ZSH_HIGHLIGHT_STYLES[comment]="fg=#4c566a"
ZSH_HIGHLIGHT_STYLES[redirection]="fg=#88c0d0"

source "$HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt AUTO_CD

# General aliases
alias ls="ls -G"
alias ll="ls -lah"
alias la="ls -A"
alias cls="clear"

alias v="nvim"
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gl="git log --oneline --graph --decorate"

# Rust aliases
alias c="cargo"
alias cb="cargo build"
alias cr="cargo run"
alias ct="cargo test"
alias cc="cargo check"
alias cl="cargo clippy"
alias cf="cargo fmt"
alias cfa="cargo fmt --all"
alias cbr="cargo build --release"

# Directory navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
